### ISSUE TITLE
exercise 3.1 in chapter 3.3 is missing

### ISSUE THREAD

**Issue by TomGijselinck** [dragonwasrobot/learn-prolog-now-exercises#34]
It is inserted before exercise 3.1 (Matryoshka Dolls) of the current solutions of this repository. The missing exercise is as follows:
![image](https://cloud.githubusercontent.com/assets/3659344/20041716/9033655a-a46d-11e6-80d8-5c5574630bc5.png)

Source: http://www.learnprolognow.org/lpnpage.php?pagetype=html&pageid=lpn-htmlse11

**Comment by th0rgall** [comment]
The exercise is present, but it's numbered 3.4 [in the repo](https://github.com/th0rgall/learn-prolog-now-exercises/blob/master/chapter-3/exercises.pl#L57).

It seems there are some minor differences in numbering & content between the book (from which these solutions were compiled) and the free online version.
